import { access, mkdir, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { assertOrgAccess, assertWritable, isReadOnly } from "../config/permissions.js";
import { assertMutationAllowed } from "../config/safety.js";
import { failure, success } from "../lib/respond.js";
import { execSfJson } from "../sf/execSf.js";
import { resolveTargetOrg } from "../sf/resolveOrg.js";

const DEFAULT_PROJECT_METADATA_ROOT = "force-app/main/default";
const DEFAULT_LWC_TARGETS = [
  "lightning__AppPage",
  "lightning__RecordPage",
  "lightning__HomePage",
];

const GenerateLwcSchema = {
  componentName: z.string().min(1),
  directory: z.string().optional(),
  outputDir: z.string().optional(),
  description: z.string().optional(),
  exposeTargets: z.array(z.string().min(1)).optional(),
  createCss: z.boolean().optional(),
  overwrite: z.boolean().optional(),
  deployAfterGenerate: z.boolean().optional(),
  targetOrg: z.string().optional(),
  deployWait: z.number().int().min(1).max(120).optional(),
  ignoreConflicts: z.boolean().optional(),
  confirm: z.boolean().optional(),
};

const GenerateFlowDefinitionSchema = {
  flowApiName: z.string().min(1),
  label: z.string().optional(),
  description: z.string().optional(),
  processType: z.enum(["AutoLaunchedFlow", "Flow"]).optional(),
  apiVersion: z.string().optional(),
  directory: z.string().optional(),
  outputDir: z.string().optional(),
  overwrite: z.boolean().optional(),
  deployAfterGenerate: z.boolean().optional(),
  targetOrg: z.string().optional(),
  deployWait: z.number().int().min(1).max(120).optional(),
  ignoreConflicts: z.boolean().optional(),
  confirm: z.boolean().optional(),
};

function assertValidApiName(name, fieldName) {
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(
      `${fieldName} must start with a letter and contain only letters, numbers, and underscores.`
    );
  }
}

function toKebabCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

async function ensureParentDirectory(path) {
  await mkdir(path, { recursive: true });
}

async function writeFileSafe(path, content, overwrite) {
  if (!overwrite) {
    try {
      await access(path, fsConstants.F_OK);
      throw new Error(`File already exists: ${path}. Pass overwrite=true to replace it.`);
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }
  }

  await writeFile(path, content, "utf8");
}

function buildLwcFiles(input) {
  const tagName = `c-${toKebabCase(input.componentName)}`;
  const js = `import { LightningElement } from "lwc";

export default class ${input.componentName} extends LightningElement {}
`;

  const html = `<template>
  <div class="slds-p-around_medium">
    <p>${escapeXml(input.componentName)} loaded.</p>
  </div>
</template>
`;

  const targets = (input.exposeTargets ?? DEFAULT_LWC_TARGETS)
    .map((target) => `    <target>${escapeXml(target)}</target>`)
    .join("\n");

  const description =
    input.description ??
    `Generated by Salesforce MCP Pro for component ${input.componentName}.`;

  const metaXml = `<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
  <apiVersion>63.0</apiVersion>
  <isExposed>true</isExposed>
  <masterLabel>${escapeXml(input.componentName)}</masterLabel>
  <description>${escapeXml(description)}</description>
  <targets>
${targets}
  </targets>
</LightningComponentBundle>
`;

  const css = `:host {
  display: block;
}
`;

  return {
    tagName,
    js,
    html,
    metaXml,
    css,
  };
}

function buildFlowXml(input) {
  const label = input.label ?? input.flowApiName.replace(/_/g, " ");
  const description =
    input.description ??
    `Baseline flow definition generated by Salesforce MCP Pro for ${input.flowApiName}.`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
  <apiVersion>${escapeXml(input.apiVersion ?? "63.0")}</apiVersion>
  <description>${escapeXml(description)}</description>
  <interviewLabel>${escapeXml(label)} {!$Flow.CurrentDateTime}</interviewLabel>
  <label>${escapeXml(label)}</label>
  <processType>${escapeXml(input.processType ?? "AutoLaunchedFlow")}</processType>
  <status>Draft</status>
</Flow>
`;
}

async function deployGeneratedSource(sourceDirOrFile, input, toolName, projectDir) {
  if (!input.deployAfterGenerate) {
    return null;
  }

  if (isReadOnly()) {
    assertWritable(toolName);
  }

  const resolvedTargetOrg = await resolveTargetOrg(input.targetOrg, {
    cwd: projectDir,
  });
  assertOrgAccess(resolvedTargetOrg);
  assertMutationAllowed({
    toolName,
    targetOrg: resolvedTargetOrg,
    confirm: input.confirm,
  });

  const args = [
    "project",
    "deploy",
    "start",
    "--target-org",
    resolvedTargetOrg,
    "--source-dir",
    sourceDirOrFile,
  ];

  if (input.deployWait !== undefined) {
    args.push("--wait", String(input.deployWait));
  }

  if (input.ignoreConflicts) {
    args.push("--ignore-conflicts");
  }

  const result = await execSfJson(args, { cwd: projectDir });
  return {
    targetOrg: resolvedTargetOrg,
    result,
  };
}

export function registerGenerationTools(server) {
  server.tool(
    "sf_generate_lwc_component",
    "Generate baseline LWC component files in the Salesforce project.",
    GenerateLwcSchema,
    async (input) => {
      try {
        assertValidApiName(input.componentName, "componentName");

        const projectDir = input.directory ?? process.cwd();
        const outputRoot =
          input.outputDir ?? join(projectDir, DEFAULT_PROJECT_METADATA_ROOT, "lwc");
        const componentDir = join(outputRoot, input.componentName);

        await ensureParentDirectory(componentDir);

        const files = buildLwcFiles(input);
        const createdFiles = [];

        const jsPath = join(componentDir, `${input.componentName}.js`);
        await writeFileSafe(jsPath, files.js, input.overwrite === true);
        createdFiles.push(jsPath);

        const htmlPath = join(componentDir, `${input.componentName}.html`);
        await writeFileSafe(htmlPath, files.html, input.overwrite === true);
        createdFiles.push(htmlPath);

        const metaPath = join(componentDir, `${input.componentName}.js-meta.xml`);
        await writeFileSafe(metaPath, files.metaXml, input.overwrite === true);
        createdFiles.push(metaPath);

        if (input.createCss) {
          const cssPath = join(componentDir, `${input.componentName}.css`);
          await writeFileSafe(cssPath, files.css, input.overwrite === true);
          createdFiles.push(cssPath);
        }

        return success({
          componentName: input.componentName,
          tagName: files.tagName,
          componentDir,
          createdFiles,
          deployment: await deployGeneratedSource(
            componentDir,
            input,
            "sf_generate_lwc_component",
            projectDir
          ),
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );

  server.tool(
    "sf_generate_flow_definition",
    "Generate a baseline Salesforce Flow metadata definition file.",
    GenerateFlowDefinitionSchema,
    async (input) => {
      try {
        assertValidApiName(input.flowApiName, "flowApiName");

        const projectDir = input.directory ?? process.cwd();
        const outputRoot =
          input.outputDir ?? join(projectDir, DEFAULT_PROJECT_METADATA_ROOT, "flows");
        await ensureParentDirectory(outputRoot);

        const xml = buildFlowXml(input);
        const flowPath = join(outputRoot, `${input.flowApiName}.flow-meta.xml`);
        await writeFileSafe(flowPath, xml, input.overwrite === true);

        return success({
          flowApiName: input.flowApiName,
          processType: input.processType ?? "AutoLaunchedFlow",
          filePath: flowPath,
          deployment: await deployGeneratedSource(
            flowPath,
            input,
            "sf_generate_flow_definition",
            projectDir
          ),
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );
}
