import { execFile } from "node:child_process";
import { constants as fsConstants } from "node:fs";
import { access, mkdir, writeFile } from "node:fs/promises";
import { platform } from "node:os";
import { dirname, join, resolve } from "node:path";
import { z } from "zod";
import {
  assertOrgAccess,
  assertWritable,
  isReadOnly,
} from "../config/permissions.js";
import { assertMutationAllowed } from "../config/safety.js";
import { failure, success } from "../lib/respond.js";
import { getJsforceConnection } from "../jsforce/connection.js";
import { execSfJson } from "../sf/execSf.js";
import { resolveTargetOrg } from "../sf/resolveOrg.js";

const GraphqlQuerySchema = {
  query: z.string().min(1),
  variables: z.record(z.unknown()).optional(),
  operationName: z.string().optional(),
  targetOrg: z.string().optional(),
  directory: z.string().optional(),
};

const UIBundleListSchema = {
  targetOrg: z.string().optional(),
  directory: z.string().optional(),
  folder: z.string().optional(),
  apiVersion: z.string().optional(),
};

const UIBundleBuildSchema = {
  bundleDirectory: z.string().min(1),
  installDependencies: z.boolean().optional(),
  buildCommand: z.string().optional(),
  directory: z.string().optional(),
};

const UIBundleScaffoldSchema = {
  bundleName: z.string().min(1),
  label: z.string().optional(),
  description: z.string().optional(),
  outputDir: z.string().optional(),
  includeTypeScript: z.boolean().optional(),
  overwrite: z.boolean().optional(),
  installDependencies: z.boolean().optional(),
  buildAfterScaffold: z.boolean().optional(),
  directory: z.string().optional(),
};

const UIBundleDeploySchema = {
  sourceDir: z.array(z.string().min(1)).min(1),
  targetOrg: z.string().optional(),
  wait: z.number().int().min(1).max(120).optional(),
  ignoreConflicts: z.boolean().optional(),
  directory: z.string().optional(),
  confirm: z.boolean().optional(),
};

const DEFAULT_UIBUNDLE_ROOT = "force-app/main/default/uiBundles";

function parseCommand(value) {
  const raw = String(value ?? "").trim();
  if (!raw) {
    throw new Error("Command cannot be empty.");
  }

  const parts = raw.split(/\s+/).filter(Boolean);
  return {
    command: parts[0],
    args: parts.slice(1),
  };
}

function assertValidBundleName(value) {
  const candidate = String(value ?? "").trim();
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(candidate)) {
    throw new Error(
      "bundleName must start with a letter and contain only letters, numbers, and underscores."
    );
  }
  return candidate;
}

function toKebabCase(value) {
  return String(value)
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function toExecutionCommand(commandName) {
  if (platform() === "win32") {
    if (commandName === "npm") {
      return "npm.cmd";
    }
    if (commandName === "npx") {
      return "npx.cmd";
    }
  }
  return commandName;
}

function runCommand(commandName, args, cwd) {
  return new Promise((resolve, reject) => {
    execFile(
      toExecutionCommand(commandName),
      args,
      {
        cwd,
        windowsHide: true,
        maxBuffer: 20 * 1024 * 1024,
      },
      (error, stdout, stderr) => {
        if (error) {
          reject(
            new Error(
              `Command failed: ${commandName} ${args.join(" ")}\n${stderr || error.message}`
            )
          );
          return;
        }

        resolve({
          stdout: String(stdout ?? ""),
          stderr: String(stderr ?? ""),
        });
      }
    );
  });
}

function tailLines(value, maxLines = 40) {
  return String(value ?? "")
    .split(/\r?\n/)
    .filter(Boolean)
    .slice(-maxLines);
}

async function ensureParentDirectory(path) {
  await mkdir(path, { recursive: true });
}

async function writeFileSafe(path, content, overwrite) {
  if (!overwrite) {
    try {
      await access(path, fsConstants.F_OK);
      throw new Error(`File already exists: ${path}. Pass overwrite=true to replace it.`);
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }
  }

  await writeFile(path, content, "utf8");
}

function buildScaffoldFiles({ bundleName, label, description, includeTypeScript }) {
  const resolvedLabel = label?.trim() || bundleName;
  const resolvedDescription =
    description?.trim() ||
    `UIBundle scaffold generated by Salesforce MCP Pro for ${bundleName}.`;
  const projectName = toKebabCase(bundleName);
  const extension = includeTypeScript ? "tsx" : "jsx";
  const viteConfigExtension = includeTypeScript ? "ts" : "js";

  const appSource = includeTypeScript
    ? `import { createRoot } from "react-dom/client";
import { App } from "./App";
import "./styles.css";

const root = document.getElementById("root");
if (!root) {
  throw new Error("Root element not found.");
}

createRoot(root).render(<App />);
`
    : `import { createRoot } from "react-dom/client";
import { App } from "./App";
import "./styles.css";

const root = document.getElementById("root");
if (!root) {
  throw new Error("Root element not found.");
}

createRoot(root).render(<App />);
`;

  const componentSource = includeTypeScript
    ? `export function App() {
  return (
    <main className="app-shell">
      <h1>${resolvedLabel}</h1>
      <p>${resolvedDescription}</p>
    </main>
  );
}
`
    : `export function App() {
  return (
    <main className="app-shell">
      <h1>${resolvedLabel}</h1>
      <p>${resolvedDescription}</p>
    </main>
  );
}
`;

  const packageJson = JSON.stringify(
    {
      name: projectName,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^19.1.0",
        "react-dom": "^19.1.0",
        "@salesforce/ui-bundle": "^10.24.0",
      },
      devDependencies: {
        vite: "^7.2.4",
        "@vitejs/plugin-react": "^5.1.1",
        "@salesforce/vite-plugin-ui-bundle": "^10.24.0",
      },
    },
    null,
    2
  );

  const metadataXml = `<?xml version="1.0" encoding="UTF-8"?>
<UIBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <masterLabel>${escapeXml(resolvedLabel)}</masterLabel>
    <description>${escapeXml(resolvedDescription)}</description>
    <isActive>true</isActive>
    <version>1</version>
</UIBundle>
`;

  const uiBundleJson = `{
  "outputDir": "dist",
  "routing": {
    "trailingSlash": "never",
    "fallback": "index.html"
  }
}
`;

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${resolvedLabel}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="src/app.${extension}"></script>
  </body>
</html>
`;

  const stylesCss = `.app-shell {
  font-family: Arial, sans-serif;
  padding: 1rem;
}
`;

  const viteConfig = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import salesforce from "@salesforce/vite-plugin-ui-bundle";
import { resolve } from "node:path";

export default defineConfig({
  base: "./",
  plugins: [react(), salesforce()],
  build: {
    outDir: resolve(__dirname, "dist"),
    assetsDir: "assets"
  }
});
`;

  return {
    includeTypeScript,
    files: [
      { relativePath: "package.json", content: `${packageJson}\n` },
      { relativePath: ".gitignore", content: "node_modules/\ndist/\n" },
      { relativePath: "ui-bundle.json", content: uiBundleJson },
      {
        relativePath: `${bundleName}.uibundle-meta.xml`,
        content: metadataXml,
      },
      { relativePath: "index.html", content: indexHtml },
      { relativePath: `src/app.${extension}`, content: appSource },
      {
        relativePath: `src/App.${includeTypeScript ? "tsx" : "jsx"}`,
        content: componentSource,
      },
      { relativePath: "src/styles.css", content: stylesCss },
      {
        relativePath: `vite.config.${viteConfigExtension}`,
        content: viteConfig,
      },
    ],
  };
}

async function requestPost(connection, path, body) {
  if (typeof connection.requestPost === "function") {
    return connection.requestPost(path, body);
  }
  return connection.request({
    method: "POST",
    url: path,
    body,
  });
}

export function registerMultiFrameworkTools(server) {
  server.tool(
    "sf_graphql_query",
    "Run a Salesforce GraphQL query in the target org.",
    GraphqlQuerySchema,
    async (input) => {
      try {
        const { targetOrg, connection } = await getJsforceConnection(input.targetOrg, {
          cwd: input.directory,
        });
        assertOrgAccess(targetOrg);

        const requestPath = `/services/data/v${connection.version}/graphql`;
        const body = {
          query: input.query,
          variables: input.variables ?? {},
        };
        if (input.operationName?.trim()) {
          body.operationName = input.operationName.trim();
        }

        const result = await requestPost(connection, requestPath, body);
        return success({
          targetOrg,
          apiVersion: connection.version,
          operationName: body.operationName ?? null,
          result,
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );

  server.tool(
    "sf_uibundle_list",
    "List UIBundle metadata components in the target org.",
    UIBundleListSchema,
    async (input) => {
      try {
        const resolvedTargetOrg = await resolveTargetOrg(input.targetOrg, {
          cwd: input.directory,
        });
        assertOrgAccess(resolvedTargetOrg);

        const args = [
          "org",
          "list",
          "metadata",
          "--metadata-type",
          "UIBundle",
          "--target-org",
          resolvedTargetOrg,
        ];
        if (input.folder?.trim()) {
          args.push("--folder", input.folder.trim());
        }
        if (input.apiVersion?.trim()) {
          args.push("--api-version", input.apiVersion.trim());
        }

        const result = await execSfJson(args, { cwd: input.directory });
        return success({
          targetOrg: resolvedTargetOrg,
          metadataType: "UIBundle",
          result,
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );

  server.tool(
    "sf_uibundle_scaffold",
    "Scaffold a starter Salesforce UIBundle project (metadata + React/Vite app files).",
    UIBundleScaffoldSchema,
    async (input) => {
      try {
        const baseDir = input.directory ?? process.cwd();
        const bundleName = assertValidBundleName(input.bundleName);
        const includeTypeScript = input.includeTypeScript === true;
        const bundleRoot = resolve(baseDir, input.outputDir ?? DEFAULT_UIBUNDLE_ROOT, bundleName);
        const overwrite = input.overwrite === true;

        const scaffold = buildScaffoldFiles({
          bundleName,
          label: input.label,
          description: input.description,
          includeTypeScript,
        });

        const createdFiles = [];
        for (const file of scaffold.files) {
          const fullPath = join(bundleRoot, file.relativePath);
          await ensureParentDirectory(dirname(fullPath));
          await writeFileSafe(fullPath, file.content, overwrite);
          createdFiles.push(fullPath);
        }

        const steps = [];
        if (input.installDependencies === true || input.buildAfterScaffold === true) {
          const installOutput = await runCommand("npm", ["install"], bundleRoot);
          steps.push({
            step: "install",
            command: "npm install",
            stdoutTail: tailLines(installOutput.stdout),
            stderrTail: tailLines(installOutput.stderr),
          });
        }

        if (input.buildAfterScaffold === true) {
          const buildOutput = await runCommand("npm", ["run", "build"], bundleRoot);
          steps.push({
            step: "build",
            command: "npm run build",
            stdoutTail: tailLines(buildOutput.stdout),
            stderrTail: tailLines(buildOutput.stderr),
          });
        }

        return success({
          bundleName,
          bundleRoot,
          includeTypeScript,
          createdFiles,
          steps,
          notes: [
            "Scaffold includes ui-bundle.json and .uibundle-meta.xml metadata.",
            "Use sf_uibundle_build for additional build command customization.",
          ],
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );

  server.tool(
    "sf_uibundle_build",
    "Run build commands in a local UIBundle project directory.",
    UIBundleBuildSchema,
    async (input) => {
      try {
        const baseDir = input.directory ?? process.cwd();
        const bundleDirectory = input.bundleDirectory;
        const bundlePath = resolve(baseDir, bundleDirectory);
        const installDependencies = input.installDependencies !== false;
        const parsedBuild = parseCommand(input.buildCommand ?? "npm run build");

        const steps = [];
        if (installDependencies) {
          steps.push({ command: "npm", args: ["install"], label: "install" });
        }
        steps.push({
          command: parsedBuild.command,
          args: parsedBuild.args,
          label: "build",
        });

        const outputs = [];
        for (const step of steps) {
          const output = await runCommand(step.command, step.args, bundlePath);
          outputs.push({
            step: step.label,
            command: `${step.command} ${step.args.join(" ")}`.trim(),
            stdoutTail: tailLines(output.stdout),
            stderrTail: tailLines(output.stderr),
          });
        }

        return success({
          bundleDirectory,
          bundlePath,
          installDependencies,
          buildCommand: `${parsedBuild.command} ${parsedBuild.args.join(" ")}`.trim(),
          steps: outputs,
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );

  server.tool(
    "sf_uibundle_deploy",
    "Deploy UIBundle source directories to a target org.",
    UIBundleDeploySchema,
    async (input) => {
      try {
        if (isReadOnly()) {
          assertWritable("sf_uibundle_deploy");
        }

        const resolvedTargetOrg = await resolveTargetOrg(input.targetOrg, {
          cwd: input.directory,
        });
        assertOrgAccess(resolvedTargetOrg);
        assertMutationAllowed({
          toolName: "sf_uibundle_deploy",
          targetOrg: resolvedTargetOrg,
          confirm: input.confirm,
        });

        const args = [
          "project",
          "deploy",
          "start",
          "--target-org",
          resolvedTargetOrg,
        ];
        for (const source of input.sourceDir) {
          args.push("--source-dir", source);
        }
        if (input.wait !== undefined) {
          args.push("--wait", String(input.wait));
        }
        if (input.ignoreConflicts) {
          args.push("--ignore-conflicts");
        }

        const result = await execSfJson(args, { cwd: input.directory });
        return success({
          targetOrg: resolvedTargetOrg,
          sourceDir: input.sourceDir,
          result,
        });
      } catch (error) {
        return failure(error.message, error.context ?? null);
      }
    }
  );
}
